sudo: required
services:
    - docker

before_install:
    - docker build -t benjaminchua/react-test -f ./client/Dockerfile.dev ./client

# test
script:
    - docker run -e CI=true benjaminchua/react-test npm test

after_success:
    - docker build -t benjaminchua/multi-client ./client
    - docker build -t benjaminchua/multi-nginx ./nginx
    - docker build -t benjaminchua/multi-server ./server
    - docker build -t benjaminchua/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push benjaminchua/multi-client
    - docker push benjaminchua/multi-nginx
    - docker push benjaminchua/multi-server
    - docker push benjaminchua/multi-worker
